// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbqGH3dBbNww7f6hPbSbixZgTXVHxE8u0',
    appId: '1:242781852491:web:8d789e36ae076298ae4ece',
    messagingSenderId: '242781852491',
    projectId: 'movie-app-4775b',
    authDomain: 'movie-app-4775b.firebaseapp.com',
    storageBucket: 'movie-app-4775b.firebasestorage.app',
    measurementId: 'G-4N78S1LNPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAccjcjYDbhSf0ZSr8W-9Ub-ZM3rD0bZuc',
    appId: '1:242781852491:android:921402a9caab22e2ae4ece',
    messagingSenderId: '242781852491',
    projectId: 'movie-app-4775b',
    storageBucket: 'movie-app-4775b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt_Uvqub902nknZwh0esKwiBD0m6A7dR8',
    appId: '1:242781852491:ios:6fcfb8b54e3a6fc3ae4ece',
    messagingSenderId: '242781852491',
    projectId: 'movie-app-4775b',
    storageBucket: 'movie-app-4775b.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt_Uvqub902nknZwh0esKwiBD0m6A7dR8',
    appId: '1:242781852491:ios:6fcfb8b54e3a6fc3ae4ece',
    messagingSenderId: '242781852491',
    projectId: 'movie-app-4775b',
    storageBucket: 'movie-app-4775b.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );
}
